"""
SMATA Core Interfaces
=====================
Abstract base classes and data structures shared across all SMATA components.
All adapters, monitors, and analysis components implement these interfaces.

Author: Saher Elsayed
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Dict, Any, Optional
import time


# ──────────────────────────────────────────────────────────────────
# Enumerations
# ──────────────────────────────────────────────────────────────────

class DriverState(Enum):
    IDLE = "idle"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    ERROR = "error"


class DriverEvent(Enum):
    SESSION_START = "session_start"
    SESSION_END = "session_end"
    TOOL_SWITCH = "tool_switch"
    CRASH_DETECTED = "crash_detected"
    ANR_DETECTED = "anr_detected"
    CHECKPOINT = "checkpoint"
    ADAPTER_INIT = "adapter_init"
    ADAPTER_STOP = "adapter_stop"


class EventType(Enum):
    TOUCH = "touch"
    LONG_PRESS = "long_press"
    SWIPE = "swipe"
    KEY_EVENT = "key_event"
    TEXT_INPUT = "text_input"
    BACK = "back"
    HOME = "home"
    MENU = "menu"
    ROTATE = "rotate"
    PINCH = "pinch"
    SCROLL = "scroll"
    NAVIGATE = "navigate"


class FailureType(Enum):
    CRASH = "crash"
    ANR = "anr"
    ASSERTION = "assertion"
    NETWORK_ERROR = "network_error"
    TIMEOUT = "timeout"
    UNKNOWN = "unknown"


class Platform(Enum):
    ANDROID = "android"
    IOS = "ios"


# ──────────────────────────────────────────────────────────────────
# Data Classes
# ──────────────────────────────────────────────────────────────────

@dataclass
class AdapterConfig:
    """Configuration passed to each adapter on initialization."""
    event_count: int = 10000
    throttle_ms: int = 50
    seed: int = 42
    timeout_s: int = 3600
    platform: Platform = Platform.ANDROID
    device_serial: Optional[str] = None
    extra_params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class InputEvent:
    """A single recorded input event."""
    event_type: EventType
    target_view_id: Optional[str] = None
    x: float = 0.0
    y: float = 0.0
    action_params: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)
    sequence_number: int = 0
    app_state_hash: Optional[str] = None
    adapter_provenance: Optional[str] = None
    screen_name: Optional[str] = None

    def to_dict(self) -> Dict:
        return {
            "seq": self.sequence_number,
            "type": self.event_type.value,
            "view": self.target_view_id,
            "x": self.x,
            "y": self.y,
            "ts": self.timestamp,
            "state_hash": self.app_state_hash,
            "adapter": self.adapter_provenance,
            "screen": self.screen_name,
            "params": self.action_params,
        }


@dataclass
class FailureSignal:
    """A detected application failure."""
    failure_type: FailureType
    message: str
    stack_trace: Optional[str] = None
    timestamp: float = field(default_factory=time.time)
    triggering_sequence_number: Optional[int] = None
    crash_package: Optional[str] = None
    activity: Optional[str] = None
    pid: Optional[int] = None

    def to_dict(self) -> Dict:
        return {
            "type": self.failure_type.value,
            "message": self.message,
            "timestamp": self.timestamp,
            "stack_trace": self.stack_trace,
            "triggering_seq": self.triggering_sequence_number,
            "activity": self.activity,
        }


@dataclass
class BugReport:
    """A reproducible bug report generated by the Sanity Checker."""
    failure: FailureSignal
    minimal_reproduction_sequence: List[InputEvent]
    full_event_count: int
    stack_trace: Optional[str] = None
    created_at: float = field(default_factory=time.time)
    reproduction_verified: bool = False
    reproduction_attempts: int = 0

    @property
    def reduction_ratio(self) -> float:
        if self.full_event_count == 0:
            return 1.0
        return len(self.minimal_reproduction_sequence) / self.full_event_count

    def to_dict(self) -> Dict:
        return {
            "failure": self.failure.to_dict(),
            "minimal_steps": len(self.minimal_reproduction_sequence),
            "full_event_count": self.full_event_count,
            "reduction_ratio": round(self.reduction_ratio, 3),
            "reproduction_verified": self.reproduction_verified,
            "reproduction_attempts": self.reproduction_attempts,
            "events": [e.to_dict() for e in self.minimal_reproduction_sequence],
        }


@dataclass
class TestRunResult:
    """Result from a single adapter time-slice execution."""
    adapter_name: str
    coverage: float = 0.0
    coverage_delta: Optional[float] = None
    event_count: int = 0
    crash_count: int = 0
    anr_count: int = 0
    unique_activities: List[str] = field(default_factory=list)
    visited_states: List[str] = field(default_factory=list)
    uncovered_activities: List[str] = field(default_factory=list)
    execution_time_s: float = 0.0
    error: Optional[str] = None

    def to_dict(self) -> Dict:
        return {
            "adapter": self.adapter_name,
            "coverage": self.coverage,
            "coverage_delta": self.coverage_delta,
            "events": self.event_count,
            "crashes": self.crash_count,
            "anrs": self.anr_count,
            "activities": len(self.unique_activities),
            "states": len(self.visited_states),
            "duration_s": self.execution_time_s,
        }


@dataclass
class SessionResult:
    """Aggregate result for a full SMATA testing session."""
    app_package: str
    run_results: List[TestRunResult] = field(default_factory=list)
    bug_reports: List[BugReport] = field(default_factory=list)
    total_events: int = 0
    total_duration_s: float = 0.0
    adapter_stats: Dict[str, Any] = field(default_factory=dict)
    errors: List[str] = field(default_factory=list)

    def add_run_result(self, adapter_name: str, result: TestRunResult) -> None:
        self.run_results.append(result)

    def add_bug_report(self, report: BugReport) -> None:
        self.bug_reports.append(report)

    def add_error(self, error: str) -> None:
        self.errors.append(error)

    @property
    def max_coverage(self) -> float:
        if not self.run_results:
            return 0.0
        return max(r.coverage for r in self.run_results)

    @property
    def total_crashes(self) -> int:
        return sum(r.crash_count for r in self.run_results)

    @property
    def total_anrs(self) -> int:
        return sum(r.anr_count for r in self.run_results)

    def to_dict(self) -> Dict:
        return {
            "app_package": self.app_package,
            "total_events": self.total_events,
            "total_duration_s": round(self.total_duration_s, 2),
            "max_coverage": round(self.max_coverage, 2),
            "total_crashes": self.total_crashes,
            "total_anrs": self.total_anrs,
            "bug_reports": len(self.bug_reports),
            "adapter_stats": self.adapter_stats,
            "run_results": [r.to_dict() for r in self.run_results],
            "errors": self.errors,
        }


@dataclass
class ObserverFeedback:
    """Feedback from Observer to Driver for tool-switching decisions."""
    should_switch_tool: bool
    coverage_delta: float
    uncovered_activities: List[str] = field(default_factory=list)
    cycle_detected: bool = False
    suggested_adapter: Optional[str] = None
    confidence: float = 1.0
    reason: str = ""


# ──────────────────────────────────────────────────────────────────
# Abstract Interfaces
# ──────────────────────────────────────────────────────────────────

class ITestAdapter(ABC):
    """
    Abstract interface for SMATA test-generation back-ends.

    All adapters (Monkey, Dynodroid, Espresso, XCUITest, etc.)
    must implement this interface to be pluggable into the Driver.
    """

    @abstractmethod
    def initialize(self, app_package: str, config: AdapterConfig) -> None:
        """Initialize the adapter for the given app."""
        ...

    @abstractmethod
    def execute(self, duration_seconds: int) -> TestRunResult:
        """Execute a test run for the given duration."""
        ...

    @abstractmethod
    def get_adapter_name(self) -> str:
        """Return the adapter's display name."""
        ...

    @abstractmethod
    def get_event_count(self) -> int:
        """Return current event count generated this session."""
        ...

    @abstractmethod
    def stop(self) -> None:
        """Gracefully stop the current run."""
        ...

    def get_current_coverage(self) -> float:
        """Return current statement coverage (0.0-100.0)."""
        return 0.0

    def get_visited_activities(self) -> List[str]:
        """Return list of visited Android activities / iOS view controllers."""
        return []

    def is_running(self) -> bool:
        """Return True if the adapter is currently executing."""
        return False

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.get_adapter_name()})"


class IMonitor(ABC):
    """Abstract interface for SMATA monitor components."""

    @abstractmethod
    def start_recording(self) -> None:
        ...

    @abstractmethod
    def stop_recording(self) -> None:
        ...

    @abstractmethod
    def get_event_count(self) -> int:
        ...


class ISequencer(ABC):
    """Abstract interface for SMATA sequencer components."""

    @abstractmethod
    def initialize(self, app_package: str) -> bool:
        ...

    @abstractmethod
    def load_script_library(self, path: str) -> None:
        ...


class IChecker(ABC):
    """Abstract interface for SMATA checker/sanity-check components."""

    @abstractmethod
    def check(self) -> Optional[BugReport]:
        ...

    @abstractmethod
    def get_bug_reports(self) -> List[BugReport]:
        ...
