"""
SMATA Input Monitor
===================
Records all input events with precise timestamps, application state hashes,
and adapter provenance. The event log is the foundation for coverage analysis
and bug reproduction (consumed by SanityChecker).

Corresponds to UVM Active Monitor adapted for mobile input streams.

Author: Saher Elsayed
"""

import time
import json
import hashlib
import threading
from pathlib import Path
from typing import List, Optional, Dict, Any, Tuple
from collections import deque
from dataclasses import dataclass

from smata.core.interfaces import InputEvent, EventType, IMonitor
from smata.utils.logger import SMATALogger

logger = SMATALogger.get_logger(__name__)


@dataclass
class MonitorConfig:
    """Configuration for the Input Monitor."""
    buffer_size: int = 100000
    flush_interval_s: float = 30.0
    persist_to_disk: bool = True
    output_path: str = "smata_output/event_log.jsonl"
    record_state_hashes: bool = True
    compress_log: bool = False
    deduplicate_consecutive: bool = False


class InputMonitor(IMonitor):
    """
    SMATA Input Monitor

    Records all input events generated by any registered ITestAdapter.
    Each event entry includes: timestamp, event type, target view,
    action parameters, application state hash, and adapter provenance.

    Thread-safe. Supports streaming writes to disk for large sessions.

    Usage:
        monitor = InputMonitor()
        monitor.start_recording()
        monitor.log_event(InputEvent(EventType.TOUCH, x=100, y=200))
        log = monitor.get_event_log()
        monitor.stop_recording()
    """

    def __init__(self, config: Optional[MonitorConfig] = None):
        self.config = config or MonitorConfig()
        self._event_log: List[InputEvent] = []
        self._recording = False
        self._lock = threading.Lock()
        self._sequence_counter = 0
        self._state_history: deque = deque(maxlen=50)
        self._last_event_hash: Optional[str] = None
        self._flush_thread: Optional[threading.Thread] = None
        self._stop_flush = threading.Event()
        self._write_buffer: List[Dict] = []
        self._stats: Dict[str, int] = {t.value: 0 for t in EventType}
        self._screen_visit_log: List[Tuple[str, float]] = []

        if self.config.persist_to_disk:
            Path(self.config.output_path).parent.mkdir(parents=True, exist_ok=True)

        logger.info(f"InputMonitor initialized | buffer_size={self.config.buffer_size}")

    # ──────────────────────────────────────────────────────────────
    # Lifecycle
    # ──────────────────────────────────────────────────────────────

    def start_recording(self) -> None:
        with self._lock:
            self._event_log.clear()
            self._sequence_counter = 0
            self._stats = {t.value: 0 for t in EventType}
            self._screen_visit_log.clear()
            self._recording = True
            self._stop_flush.clear()

        if self.config.persist_to_disk and self.config.flush_interval_s > 0:
            self._flush_thread = threading.Thread(
                target=self._periodic_flush, daemon=True)
            self._flush_thread.start()

        logger.info("InputMonitor: recording started")

    def stop_recording(self) -> None:
        with self._lock:
            self._recording = False

        self._stop_flush.set()
        if self._flush_thread and self._flush_thread.is_alive():
            self._flush_thread.join(timeout=5)

        if self.config.persist_to_disk:
            self._flush_to_disk(final=True)

        logger.info(f"InputMonitor: recording stopped | "
                    f"events={len(self._event_log)} | "
                    f"unique_screens={len(set(s for s, _ in self._screen_visit_log))}")

    # ──────────────────────────────────────────────────────────────
    # Event Logging
    # ──────────────────────────────────────────────────────────────

    def log_event(self, event: InputEvent) -> int:
        """
        Log a single input event.

        Called by each ITestAdapter for every event it generates.
        Returns the assigned sequence number.
        """
        if not self._recording:
            return -1

        with self._lock:
            if len(self._event_log) >= self.config.buffer_size:
                logger.warning("Event buffer full — oldest events will be dropped.")
                self._event_log.pop(0)

            # Deduplication
            if self.config.deduplicate_consecutive:
                event_hash = self._hash_event(event)
                if event_hash == self._last_event_hash:
                    return self._sequence_counter
                self._last_event_hash = event_hash

            # Assign metadata
            event.timestamp = time.time()
            event.sequence_number = self._sequence_counter
            self._sequence_counter += 1

            # State hash
            if self.config.record_state_hashes and event.app_state_hash is None:
                event.app_state_hash = self._compute_state_hash(event)

            self._event_log.append(event)
            self._stats[event.event_type.value] += 1

            # Track screen visits
            if event.screen_name:
                self._screen_visit_log.append((event.screen_name, event.timestamp))

            # Buffer for disk write
            if self.config.persist_to_disk:
                self._write_buffer.append(event.to_dict())

            return event.sequence_number

    def log_touch(self, x: float, y: float, view_id: Optional[str] = None,
                  adapter: Optional[str] = None, screen: Optional[str] = None) -> int:
        """Convenience method for logging touch events."""
        return self.log_event(InputEvent(
            event_type=EventType.TOUCH,
            x=x, y=y,
            target_view_id=view_id,
            adapter_provenance=adapter,
            screen_name=screen,
        ))

    def log_text_input(self, text: str, view_id: Optional[str] = None,
                       adapter: Optional[str] = None) -> int:
        """Convenience method for logging text input events."""
        return self.log_event(InputEvent(
            event_type=EventType.TEXT_INPUT,
            target_view_id=view_id,
            action_params={"text": text},
            adapter_provenance=adapter,
        ))

    def log_navigation(self, action: str, target: Optional[str] = None,
                       adapter: Optional[str] = None) -> int:
        """Convenience method for logging navigation events."""
        return self.log_event(InputEvent(
            event_type=EventType.NAVIGATE,
            action_params={"action": action, "target": target},
            adapter_provenance=adapter,
        ))

    def log_key_event(self, key_code: int, adapter: Optional[str] = None) -> int:
        """Convenience method for logging key events."""
        return self.log_event(InputEvent(
            event_type=EventType.KEY_EVENT,
            action_params={"key_code": key_code},
            adapter_provenance=adapter,
        ))

    # ──────────────────────────────────────────────────────────────
    # Log Access
    # ──────────────────────────────────────────────────────────────

    def get_event_log(self) -> List[InputEvent]:
        """Return the full ordered event log (immutable snapshot)."""
        with self._lock:
            return list(self._event_log)

    def get_event_log_from(self, seq_num: int) -> List[InputEvent]:
        """Return the event log from a given sequence number onwards."""
        with self._lock:
            return [e for e in self._event_log if e.sequence_number >= seq_num]

    def get_event_log_in_range(self, start_ts: float,
                                end_ts: float) -> List[InputEvent]:
        """Return events within a timestamp range."""
        with self._lock:
            return [e for e in self._event_log
                    if start_ts <= e.timestamp <= end_ts]

    def get_events_by_type(self, event_type: EventType) -> List[InputEvent]:
        """Return all events of a specific type."""
        with self._lock:
            return [e for e in self._event_log if e.event_type == event_type]

    def get_events_by_adapter(self, adapter_name: str) -> List[InputEvent]:
        """Return all events generated by a specific adapter."""
        with self._lock:
            return [e for e in self._event_log
                    if e.adapter_provenance == adapter_name]

    def get_events_preceding(self, seq_num: int,
                              window: int = 100) -> List[InputEvent]:
        """Return up to `window` events preceding a given sequence number."""
        with self._lock:
            preceding = [e for e in self._event_log
                         if e.sequence_number < seq_num]
            return preceding[-window:]

    def get_event_count(self) -> int:
        return self._sequence_counter

    def get_stats(self) -> Dict[str, Any]:
        """Return event type distribution statistics."""
        with self._lock:
            unique_screens = len(set(s for s, _ in self._screen_visit_log))
            return {
                "total_events": self._sequence_counter,
                "recording": self._recording,
                "event_types": dict(self._stats),
                "unique_screens_visited": unique_screens,
                "screen_visits": len(self._screen_visit_log),
            }

    def get_unique_screens(self) -> List[str]:
        """Return list of unique screens visited."""
        with self._lock:
            return list(dict.fromkeys(s for s, _ in self._screen_visit_log))

    def get_screen_visit_frequency(self) -> Dict[str, int]:
        """Return visit count per screen."""
        freq: Dict[str, int] = {}
        with self._lock:
            for screen, _ in self._screen_visit_log:
                freq[screen] = freq.get(screen, 0) + 1
        return freq

    # ──────────────────────────────────────────────────────────────
    # Internal Utilities
    # ──────────────────────────────────────────────────────────────

    def _hash_event(self, event: InputEvent) -> str:
        """Compute a hash for deduplication."""
        key = f"{event.event_type.value}|{event.x:.0f}|{event.y:.0f}|{event.target_view_id}"
        return hashlib.md5(key.encode()).hexdigest()[:8]

    def _compute_state_hash(self, event: InputEvent) -> str:
        """Compute an approximate application state hash from recent events."""
        recent = self._event_log[-5:] if len(self._event_log) >= 5 else self._event_log
        state_key = "|".join(
            f"{e.event_type.value}:{e.target_view_id}" for e in recent
        )
        return hashlib.md5(state_key.encode()).hexdigest()[:12]

    def _periodic_flush(self) -> None:
        """Background thread: periodically flush write buffer to disk."""
        while not self._stop_flush.wait(timeout=self.config.flush_interval_s):
            self._flush_to_disk(final=False)

    def _flush_to_disk(self, final: bool = False) -> None:
        with self._lock:
            buffer = self._write_buffer[:]
            self._write_buffer.clear()

        if not buffer:
            return

        mode = "a"
        try:
            with open(self.config.output_path, mode) as f:
                for entry in buffer:
                    f.write(json.dumps(entry) + "\n")
            if final:
                logger.info(f"Event log flushed to {self.config.output_path} "
                            f"({self._sequence_counter} total events)")
        except IOError as e:
            logger.error(f"Failed to write event log: {e}")

    def export_json(self, path: str) -> None:
        """Export the full event log to a JSON file."""
        with self._lock:
            data = {
                "metadata": self.get_stats(),
                "events": [e.to_dict() for e in self._event_log],
            }
        with open(path, "w") as f:
            json.dump(data, f, indent=2)
        logger.info(f"Event log exported to {path}")

    def clear(self) -> None:
        """Clear the event log and reset counters."""
        with self._lock:
            self._event_log.clear()
            self._sequence_counter = 0
            self._stats = {t.value: 0 for t in EventType}
            self._screen_visit_log.clear()
            self._write_buffer.clear()

    def __len__(self) -> int:
        return self._sequence_counter

    def __repr__(self) -> str:
        return (f"InputMonitor(events={self._sequence_counter}, "
                f"recording={self._recording})")
